sudo: required

services:
  - docker

before_install:
  - docker build -t benchmarks .

script:
  - docker run benchmarks ./jobs/himeno_local_M_single.sh

notifications:
  slack: microbrain:dHXYnMz4KBlHXHLs64ju5h5Y
